name: SSH EC2 | Run Image QA Enviroment

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_VENTAS_TEST }}
          username: ${{ secrets.QA_VENTAS_USER }}
          key: ${{ secrets.SSH_VENTAS_TEST }}
          script: |
            sudo su                     # Cambiar a super usuario
            yum update -y               # Actualizar
            yum install docker -y       # Instalar Docker
            systemctl start docker      # Iniciarlizar el servicio
            systemctl enable docker
            
            # Descargar la imagen
            docker pull diego1986/qa_ventas_diego_ormeno:latest  

            # Ejecutar el contenedor
            docker run -d --name ventas_container -p 3000:3000 --restart always diego1986/qa_ventas_diego_ormeno:latest

      - name: Wait for service to start
        run: sleep 30  # Espera 30 segundos antes de continuar

      - name: Execute curl command
        run: |
          sudo curl -v ${{ secrets.HOST_VENTAS_TEST }}:3000



