name: SSH EC2 | Run Image QA Enviroment

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_VENTAS_TEST }}
          username: ${{ secrets.QA_VENTAS_USER }}
          key: ${{ secrets.SSH_VENTAS_TEST }}
          script: |
            sudo yum update -y
            sudo yum install docker -y
            sudo systemctl start docker
            sudo systemctl enable docker
            
            # Verificar si existe un contenedor con el mismo nombre y eliminarlo si es así
            sudo docker rm -f ventas_container || true
            
            sudo docker pull diego1986/qa_ventas_diego_ormeno:latest
            sudo docker run -d --name ventas_container -p ${{ secrets.HOST_VENTAS_TEST }}:3000:3000 --restart always diego1986/qa_ventas_diego_ormeno:latest

      - name: Perform curl request
        run: |
          curl http://${{ secrets.HOST_VENTAS_TEST }}:3000

