name: Trivy Scanner

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/neo4j:4.4.32-enterprise'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'



