name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/neo4j:5.18.0-community-ubi9'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1' # Set exit code to 1 to make the step fail if vulnerabilities are found

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Fail the pipeline if Trivy scan step fails (indicating vulnerabilities were found)
      - name: Check Trivy scan status
        if: ${{ failure() }}
        run: echo "Trivy scan failed due to vulnerabilities found, failing the pipeline." && exit 1

    
    
   

