name: remote_ssh_command_ventas

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_PRUEBA_HOST }}
          username: ${{ secrets.QA_PRUEBA_USER }}
          key: ${{ secrets.QA_PRUEBA_SSH }}
          script: |
            sudo yum update -y
            sudo yum install -y nodejs npm git docker
            sudo rm -rf /opt/ventas-qa
            sudo mkdir -p /opt/ventas-qa
            cd /opt/ventas-qa
            sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/rijmjada/sprint-2 .

      - name: Construir imagen Docker
        run: |
          sudo systemctl start docker
          sudo docker build -t ventas-qa .
        working-directory: /opt/ventas-qa

      - name: Etiquetar imagen Docker
        run: |
          sudo docker tag ventas-qa diego1986/qa_ventas_diego_ormeno:latest
        working-directory: /opt/ventas-qa

      - name: Iniciar sesión en Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Empujar imagen a Docker Hub
        run: |
          sudo docker push diego1986/qa_ventas_diego_ormeno:latest
        working-directory: /opt/ventas-qa
