name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/neo4j:5.18.0-community-ubi9'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Store the exit code in an output variable
      - name: Store Trivy scan exit code
        if: always() # This step always runs to store the exit code
        id: store_exit_code
        run: echo "::set-output name=trivy_exit_code::${{ steps.trivy_scan.outputs.exit_code }}"

      # Final step to fail the pipeline if Trivy scan had exit code 0
      - name: Fail pipeline if Trivy scan had exit code 0
        if: ${{ steps.store_exit_code.outputs.trivy_exit_code == '0' }}
        run: exit 1


    
    
   

