name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/diego1986/qa_ventas_diego_ormeno'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Final step to fail the pipeline if Trivy scan had exit code 0
      - name: Fail pipeline if Trivy scan had exit code 0
        if: ${{ steps.trivy_scan.outputs.exit-code == '0' }}
        run: exit 1


