name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/debian:9'
          exit-code: '1'  # Cambia el exit-code a '1' para que falle si se encuentran vulnerabilidades
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
          trivy-config: trivy.yaml

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() }}  # Esta acción siempre se ejecutará, independientemente del resultado del escaneo
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Fail workflow if vulnerabilities found
        if: ${{ steps.trivy_scan.outputs.exit-code == '1' }}  # Si el escaneo falló (exit-code es '1'), la acción se ejecuta
        run: exit 1  # Fuerza el fallo de la ejecución si se encuentran vulnerabilidades
