name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    permissions:
      actions: read
      contents: read
      security-events: write
  
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/library/neo4j:4.4.32'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0' # Este codigo esta invertido para continue con el upload sarif 0 es que fallo 

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check exit code
        run: |
          if [ ${{ steps.trivy_scan.outputs.exit_code }} -eq 0 ]; then
            echo "Trivy scan succeeded with exit code 0, failing the pipeline."
            exit 1
          fi


    
    
   

