name: Trivy Scanner
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/diego1986/qa_ventas_diego_ormeno:latest'
          format: 'table' # Cambiado a 'table' en lugar de 'sarif'
      
      - name: Save Trivy scan results
        run: |
          trivy docker.io/diego1986/qa_ventas_diego_ormeno:latest --format=json > trivy-results.json
      
      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.json
