name: VENTAS-EC2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          scritp: |
            sudo wget https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh -O script.sh



            
          

