name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Copy script from GitHub to remote server
        uses: appleboy/scp-action@master
        with:
        
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          scritp: |
            sudo wget https://${{ secrets.GH_TOKEN }}@raw.githubusercontent.com/alkemyTech/UMSA-DevOps-T4/main/script.sh -O script.sh


            
          

