name: VENTAS-EC2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          script: |
            sudo wget https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh -O /home/ec2-user/script.sh
            sudo bash /home/ec2-user/script.sh
