name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER_VENTAS }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          script: |
            sudo yum update -y
            sudo yum install -y nodejs npm git

      

