name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Copy script from GitHub to remote server
        uses: appleboy/scp-action@master
        with:
        
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          source: "https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh" # Ruta del script en GitHub
          target: "/home/${{ secrets.USER }}/script.sh" # Ruta en la instancia de EC2

            
          

