name: VENTAS-EC2

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_AUDITORIA_TEST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_AUDITORIA_TEST }}
          source: "https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh" # Ruta del script en GitHub
          target: "/home/script.sh" # Ruta en la instancia de EC2


            
          

