name: Trivy and ZAP Scanner Repository
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image
        run: |
          sudo docker pull diego1986/qa_ventas_diego_ormeno:latest
          sudo docker run -d --name ventas_container -p 3000:3000 --restart always diego1986/qa_ventas_diego_ormeno:latest

      - name: Run ZAP vulnerability scanner
        uses: zaproxy/action-full-scan@v0.8
        with:
          target: "http://localhost:3000"
          policy: "Light"
          report: "zap-report.html"
