name: remote_ssh_command_ventas

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_PRUEBA_HOST }}
          username: ${{ secrets.QA_PRUEBA_USER }}
          key: ${{ secrets.QA_PRUEBA_SSH }}
          script: |
            sudo yum update -y
            sudo yum install -y nodejs npm git
            sudo rm -rf /opt/ventas-qa
            sudo mkdir -p /opt/ventas-qa
            cd /opt/ventas-qa
            sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/rijmjada/sprint-2 .
