name: Run ZAP vulnerability scanner
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and run Docker image
        run: |
          sudo docker run -d -p 3000:3000 --restart always neo4j:5-ubi9

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: true
          token: ${{ secrets.GB_TOKEN }}

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap_scan_report
          path: ${{ github.workspace }}/zap-report.html
